export { default as logo } from '@/assets/logo.png'
export { default as logotipo } from '@/assets/logotipo.png'
export { default as imgMain } from '@/assets/img-main.png'
export { default as imgGirlsStudy } from '@/assets/img-girls-study.png'
export { default as bgPortada } from '@/assets/bg-portada.jpg'
